package constants

const (
	ErrorConfiguringAPIURL           = "error while configuring API server URL"
	ErrorGeneratingOperatorChallenge = "error while generating operator challenge"
	ErrorOperatorSignIn              = "error while performing operator signin"
	ErrorCreatingOperator            = "error while creating operator"
	ErrorStoringSession              = "error while storing file path configuration"
	ErrorDescriptionSize             = "description is over 200 characters"
	ErrorRetrievingOperator          = "error while retrieving operator id"
	ErrorForgingOperatorDeleteToken  = "error while forging operator delete token"
	ErrorDeletingTenant              = "error while deleting tenant"

	ErrorImageURL            = "image url is not adequate"
	ErrorLoadingConfig       = "error while loading file path configuration"
	ErrorGeneratingToken     = "error while generating access and refresh tokens"
	ErrorParsingJsonSettings = "error while parsing json settings"
	ErrorOpeningJson         = "error while opening json file"
	ErrorWritingCvsRecord    = "error writing record to csv"
	ErrorFlush               = "error occurred during the Flush"
	ErrorRetrievingField     = "error while retrieving field"
	ErrorRequiredField       = "error required flag(s)"
	ErrorRunningField        = "error while running input(s)"

	ErrorCreatingTenant                  = "error while creating tenant"
	ErrorEditingTenant                   = "error while editing tenant"
	ErrorRetrievingTenant                = "error while retrieving tenant"
	ErrorRetrievingTenantList            = "error while retrieving tenant list"
	ErrorRetrievingTenantDescription     = "error while retrieving tenant description"
	ErrorTenantNameOrID                  = "error, tenant name or id incorrect"
	ErrorRetrievingAvailableTenantSwarms = "error while retrieving available tenant swarms list"
	ErrorInvitingOperator                = "error while inviting operator"
	ErrorListingOperators                = "error while listing operators"
	ErrorRemovingOperator                = "error while removing operator"

	ErrorEmptyToken                         = "access token cannot be empty"
	ErrorRefreshToken                       = "refresh token cannot be empty"
	ErrorGeneratingOperatorChallengeRequest = "failed request to generate operator challenge"
	ErrorGettingOperatorRequest             = "failed request to get operator"
	ErrorSignRequest                        = "failed request to sign in"
	ErrorTokenExpiration                    = "wrong token expiration returned"
	ErrorTokenNotFound                      = "error token not found"

	ErrorCreatingOperatorRequest    = "failed to create operator request"
	ErrorForgingRequest             = "failed to forge token request"
	ErrorListingTenantsRequest      = "failed request to list tenants request"
	ErrorDeletingTenantRequest      = "failed request to delete tenant"
	ErrorEditingTenantRequest       = "failed request to edit tenant "
	ErrorListingTenantSwarmsRequest = "failed request to list tenant available swarms"
	ErrorInvitingOperatorRequest    = "failed request to invite operator"
	ErrorListingOperatorsRequest    = "failed request to list operators"
	ErrorRemovingOperatorRequest    = "failed request to remove operator"

	ErrorIamConfigNotFound         = "iam api server url is not defined in configuration"
	ErrorHiveConfigNotFound        = "hive api server url is not defined in configuration"
	ErrorTokenConfigNotFound       = "refresh token is not defined in configuration file"
	ErrorNameConfigNotFound        = "name is not defined in configuration file"
	ErrorDashConfigNotFound        = "dash api server url is not defined in configuration"
	ErrorSessionTypeConfigNotFound = "session type is not defined in configuration"
	ErrorSessionTypeConfigInvalid  = "session type is invalid for this request"

	ErrorCreatingSwarm           = "error while creating swarm"
	ErrorRetrievingSwarm         = "error while retrieving swarm"
	ErrorRetrievingSwarmList     = "error retrieving swarm list"
	ErrorDeletingSwarm           = "error while deleting swarm"
	ErrorEditingSwarmDescription = "error while editing swarm description"
	ErrorEditingSwarmName        = "error while retrieving swarm name"
	ErrorSwarmNameOrID           = "error, swarm name or id incorrect"

	ErrorConnectingSwarm        = "error while connecting swarm "
	ErrorCreatingSwarmRequest   = "failed request to create the swarm"
	ErrorListingSwarmsRequest   = "failed request to list swarms"
	ErrorRetrievingSwarmRequest = "failed request to get swarm"
	ErrorEditingSwarmRequest    = "failed request to edit swarm"
	ErrorDeletingSwarmRequest   = "failed request to delete swarm"
	ErrorConnectingSwarmRequest = "failed request to connect swarm"

	ErrorListingPolicies        = "error while retrieving list policies"
	ErrorListingPoliciesRequest = "failed request to list policies"

	ErrorCreatingDistributor             = "error while creating distributor"
	ErrorRetrievingDistributorList       = "error retrieving distributor list"
	ErrorDeletingDistributor             = "error while deleting distributor"
	ErrorRetrievingDistributor           = "error while retrieving distributor"
	ErrorCreatingDistributorCoupon       = "error while creating distributor coupon"
	ErrorRetrievingDistributorCouponList = "error retrieving distributor coupon list"
	ErrorDeletingDistributorCoupon       = "error while deleting distributor coupon"
	ErrorRetrievingDistributorCoupon     = "error retrieving distributor coupon"
	ErrorEditingDistributorCoupon        = "error editing distributor coupon"
	ErrorRevokingDistributorCoupon       = "error revoking distributor coupon code"
	ErrorRemovingDistributorCoupon       = "error removing distributor coupon code"

	ErrorCreatingDistributorRequest          = "failed request to create the distributor"
	ErrorListingDistributorsRequest          = "failed request to list distributors"
	ErrorDeletingDistributorRequest          = "failed request to delete distributor"
	ErrorCreatingDistributorCouponRequest    = "failed request to create the distributor coupon"
	ErrorListingDistributorCouponsRequest    = "failed request to list distributor coupons"
	ErrorRetrievingDistributorCouponRequest  = "failed request to retrieve distributor coupon"
	ErrorEditingDistributorCouponRequest     = "failed request to edit distributor coupon"
	ErrorRemovingDistributorCouponRequest    = "failed request to remove distributor coupon code"
	ErrorRetrievingDistributorRequest        = "failed request to retrieve distributor"
	ErrorRevokingDistributorCouponRequest    = "failed request to revoke distributor coupon code"
	ErrorRetrievingDistributorReportRequest  = "failed request to retrieve distributor report"
	ErrorDownloadingDistributorReportRequest = "failed request to download distributor report"

	ErrorRedemptionValue = "redemption count must be an integer"

	ErrorRetrievingOperatorRequest            = "failed request to retrieve operator"
	ErrorForgingDistributorDeleteTokenRequest = "failed request to forge distributor delete token"
	ErrorOperatorSignInRequest                = "failed request to signin operator"
	ErrorForgingOperatorDeleteTokenRequest    = "failed request to forge operator delete token"
	ErrorForgingTenantDeleteTokenRequest      = "failed request to forge tenant delete token"

	ErrorCreatingTenantRequest = "failed request to create the tenant"

	ErrorInvalidZone            = "invalid zone"
	ErrorRetrievingZonesRequest = "failed request to retrieve zones"

	ErrorCreatingProjectRequest = "failed request to create the project"
)
