package constants

const (
	ErrorConfiguringAPIURL           = "error while configuring API server URL"
	ErrorGeneratingOperatorChallenge = "error while generating operator challenge"
	ErrorOperatorSignIn              = "error while performing operator signin"
	ErrorCreatingOperator            = "error while creating operator"
	ErrorStoringSession              = "error while storing file path configuration"
	ErrorDescriptionSize             = "description is over 200 characters"
	ErrorRetrievingOperator          = "error while retrieving operator id"
	ErrorForgingOperatorDeleteToken  = "error while forging operator delete token"
	ErrorDeletingTenant              = "error while deleting tenant"

	ErrorImageURL                = "image url is not adequate"
	ErrorLoadingConfig           = "error while loading file path configuration"
	ErrorGeneratingToken         = "error while generating access and refresh tokens"
	ErrorParsingJsonSettings     = "error while parsing json settings"
	ErrorMarshallingJsonSettings = "error while marshalling json settings"
	ErrorOpeningJson             = "error while opening json file"
	ErrorWritingCvsRecord        = "error writing record to csv"
	ErrorFlush                   = "error occurred during the Flush"
	ErrorRetrievingField         = "error while retrieving field"
	ErrorRequiredField           = "error required flag(s)"
	ErrorRunningField            = "error while running input(s)"

	ErrorCreatingTenant                  = "error while creating tenant"
	ErrorEditingTenant                   = "error while editing tenant"
	ErrorRetrievingTenant                = "error while retrieving tenant"
	ErrorRetrievingTenantList            = "error while retrieving tenant list"
	ErrorRetrievingTenantDescription     = "error while retrieving tenant description"
	ErrorTenantNameOrID                  = "error, tenant name or id incorrect"
	ErrorRetrievingAvailableTenantSwarms = "error while retrieving available tenant swarms list"
	ErrorInvitingOperator                = "error while inviting operator"
	ErrorListingOperators                = "error while listing operators"
	ErrorRemovingOperator                = "error while removing operator"

	ErrorEmptyToken                         = "access token cannot be empty"
	ErrorRefreshToken                       = "refresh token cannot be empty"
	ErrorGeneratingOperatorChallengeRequest = "failed request to generate operator challenge"
	ErrorGettingOperatorRequest             = "failed request to get operator"
	ErrorSignRequest                        = "failed request to sign in"
	ErrorTokenExpiration                    = "wrong token expiration returned"
	ErrorTokenNotFound                      = "error token not found"

	ErrorCreatingOperatorRequest    = "failed to create operator request"
	ErrorPromotingOperatorRequest   = "failed to promote operator request"
	ErrorForgingRequest             = "failed to forge token request"
	ErrorListingTenantsRequest      = "failed request to list tenants request"
	ErrorDeletingTenantRequest      = "failed request to delete tenant"
	ErrorEditingTenantRequest       = "failed request to edit tenant "
	ErrorListingTenantSwarmsRequest = "failed request to list tenant available swarms"
	ErrorInvitingOperatorRequest    = "failed request to invite operator"
	ErrorListingOperatorsRequest    = "failed request to list operators"
	ErrorRemovingOperatorRequest    = "failed request to remove operator"
	ErrorEditingOperatorRoleRequest = "failed request to edit operator role"

	ErrorIamConfigNotFound          = "iam api server url is not defined in configuration"
	ErrorTokenConfigNotFound        = "refresh token is not defined in configuration file"
	ErrorNameConfigNotFound         = "name is not defined in configuration file"
	ErrorDashConfigNotFound         = "dash api server url is not defined in configuration"
	ErrorChConfigNotFound           = "ch api server url is not defined in configuration"
	ErrorMetricsConfigNotFound      = "metrics api server url is not defined in configuration"
	ErrorSwarmGatewayConfigNotFound = "swarm gateway api server url is not defined in configuration"
	ErrorSessionTypeConfigNotFound  = "session type is not defined in configuration"
	ErrorSessionTypeConfigInvalid   = "session type is invalid for this request"

	ErrorCreatingSwarm           = "error while creating swarm"
	ErrorRetrievingSwarm         = "error while retrieving swarm"
	ErrorRetrievingSwarmList     = "error retrieving swarm list"
	ErrorDeletingSwarm           = "error while deleting swarm"
	ErrorEditingSwarmDescription = "error while editing swarm description"
	ErrorEditingSwarmName        = "error while retrieving swarm name"
	ErrorSwarmNameOrID           = "error, swarm name or id incorrect"

	ErrorConnectingSwarm        = "error while connecting swarm "
	ErrorCreatingSwarmRequest   = "failed request to create the swarm"
	ErrorListingSwarmsRequest   = "failed request to list swarms"
	ErrorRetrievingSwarmRequest = "failed request to get swarm"
	ErrorEditingSwarmRequest    = "failed request to edit swarm"
	ErrorDeletingSwarmRequest   = "failed request to delete swarm"
	ErrorConnectingSwarmRequest = "failed request to connect swarm"

	ErrorListingPolicies        = "error while retrieving list policies"
	ErrorListingPoliciesRequest = "failed request to list policies"

	ErrorCreatingDistributor                       = "error while creating distributor"
	ErrorRetrievingDistributorList                 = "error retrieving distributor list"
	ErrorDeletingDistributor                       = "error while deleting distributor"
	ErrorRetrievingDistributor                     = "error while retrieving distributor"
	ErrorCreatingDistributorCoupon                 = "error while creating distributor code"
	ErrorRetrievingDistributorCouponList           = "error retrieving distributor code list"
	ErrorDeletingDistributorCoupon                 = "error while deleting distributor code"
	ErrorRetrievingDistributorCoupon               = "error retrieving distributor code"
	ErrorEditingDistributorCoupon                  = "error editing distributor code"
	ErrorRevokingDistributorCoupon                 = "error revoking distributor code"
	ErrorRemovingDistributorCoupon                 = "error removing distributor code"
	ErrorRetrievingDistributorCouponBasePolicyList = "error retrieving distributor code base policy list"

	ErrorCreatingDistributorRequest          = "failed request to create the distributor"
	ErrorListingDistributorsRequest          = "failed request to list distributors"
	ErrorDeletingDistributorRequest          = "failed request to delete distributor"
	ErrorCreatingDistributorCouponRequest    = "failed request to create the distributor code"
	ErrorListingDistributorCouponsRequest    = "failed request to list distributor codes"
	ErrorRetrievingDistributorCouponRequest  = "failed request to retrieve distributor code"
	ErrorEditingDistributorCouponRequest     = "failed request to edit distributor code"
	ErrorRemovingDistributorCouponRequest    = "failed request to remove distributor code"
	ErrorRetrievingDistributorRequest        = "failed request to retrieve distributor"
	ErrorRevokingDistributorCouponRequest    = "failed request to revoke distributor code"
	ErrorRetrievingDistributorReportRequest  = "failed request to retrieve distributor report"
	ErrorDownloadingDistributorReportRequest = "failed request to download distributor report"
	ErrorInvitingDistributorCouponRequest    = "failed request to invite to distributor code"

	ErrorRedemptionValue = "redemption count must be an integer"

	ErrorRetrievingOperatorRequest            = "failed request to retrieve operator"
	ErrorForgingDistributorDeleteTokenRequest = "failed request to forge distributor delete token"
	ErrorOperatorSignInRequest                = "failed request to signin operator"
	ErrorForgingOperatorDeleteTokenRequest    = "failed request to forge operator delete token"
	ErrorForgingTenantDeleteTokenRequest      = "failed request to forge tenant delete token"

	ErrorCreatingTenantRequest = "failed request to create the tenant"

	ErrorInvalidZone            = "invalid zone"
	ErrorRetrievingZonesRequest = "failed request to retrieve zones"

	ErrorCreatingProjectRequest = "failed request to create the project"

	ErrorListingTenantAccountsRequest           = "failed request to list tenant users"
	ErrorDeletingTenantAccountRequest           = "failed request to delete tenant user"
	ErrorDescribingTenantAccountRequest         = "failed request to describe tenant user"
	ErrorEditingTenantAccountRequest            = "failed request to edit tenant user"
	ErrorFreezingTenantAccountRequest           = "failed request to freeze tenant user"
	ErrorUnfreezingTenantAccountRequest         = "failed request to unfreeze tenant user"
	ErrorRestoringTenantAccountRequest          = "failed request to restore tenant user"
	ErrorDeletingTenantAccountSessionsRequest   = "failed request to delete tenant user sessions"
	ErrorRetrievingTenantAccountRequest         = "failed request to retrieve tenant user"
	ErrorForgingTenantAccountDeleteTokenRequest = "failed request to forge tenant user delete token"
	ErrorCreatingTenantAccountsRequest          = "failed request to create tenant users"
	ErrorUpdatingTenantAccountRequest           = "failed request to update tenant user"
	ErrorParsingMaxAllowedProjects              = "error while parsing max allowed projects"

	ErrorInvalidInternalValue = "invalid internal value"

	ErrorListingTenantProjectsRequest           = "failed request to list tenant projects"
	ErrorDeletingTenantProjectRequest           = "failed request to delete tenant project"
	ErrorDescribingTenantProjectRequest         = "failed request to describe tenant project"
	ErrorEditingTenantProjectRequest            = "failed request to edit tenant project"
	ErrorFreezingTenantProjectRequest           = "failed request to freeze tenant project"
	ErrorUnfreezingTenantProjectRequest         = "failed request to unfreeze tenant project"
	ErrorRestoringTenantProjectRequest          = "failed request to restore tenant project"
	ErrorRetrievingTenantProjectRequest         = "failed request to retrieve tenant project"
	ErrorForgingTenantProjectDeleteTokenRequest = "failed request to forge tenant project delete token"
	ErrorUpdatingTenantProjectRequest           = "failed request to update tenant project"

	ErrorCreatingNexusRequest   = "failed request to create nexus"
	ErrorListingNexusesRequest  = "failed request to list nexuses"
	ErrorDeletingNexusRequest   = "failed request to delete nexus"
	ErrorEditingNexusRequest    = "failed request to edit nexus"
	ErrorRetrievingNexusRequest = "failed request to retrieve nexus"

	ErrorCreatingNodeRequest     = "failed request to create node"
	ErrorListingNodesRequest     = "failed request to list nodes"
	ErrorDeletingNodeRequest     = "failed request to delete node"
	ErrorEditingNodeRequest      = "failed request to edit node"
	ErrorRetrievingNodeRequest   = "failed request to retrieve node"
	ErrorCreatingSwarmSecret     = "failed request to create swarm secret"
	ErrorListingProvidersRequest = "failed request to list providers"

	ErrorCreatingRedundancyClassRequest   = "failed request to create redundancy class"
	ErrorListingRedundancyClassesRequest  = "failed request to list redundancy classes"
	ErrorRetrievingRedundancyClassRequest = "failed request to retrieve redundancy class"

	ErrorConvertingField     = "error while converting field"
	ErrorNotEnoughNodes      = "not enough nodes"
	ErrorNotEnoughNexuses    = "not enough nexuses"
	ErrorCreatingRingRequest = "failed request to create ring"
	ErrorListingRingsRequest = "failed request to list rings"

	ErrorParsingJsonConfiguration = "error while parsing json configuration"

	ErrorRetrievingAgentRequest                       = "failed request to retrieve agent"
	ErrorEditingAgentRequest                          = "failed request to edit agent"
	ErrorListingAgentsRequest                         = "failed request to list agents"
	ErrorCheckingRedundancyClassStatusRequest         = "failed request to check redundancy class status"
	ErrorCheckingRedundancyClassRecoveryStatusRequest = "failed request to check redundancy class recovery status"
	ErrorRecoveringRedundancyClassRequest             = "failed request to recover redundancy class"
	ErrorExpandingRedundancyClassRequest              = "failed request to expand redundancy class"

	ErrorRetrievingTenantReportRequest  = "failed request to retrieve tenant report"
	ErrorDownloadingTenantReportRequest = "failed request to download tenant report"
)
