load("@io_bazel_rules_go//go:def.bzl", "go_library")

go_library(
    name = "utils",
    srcs = [
        "crypto.go",
        "slices.go",
    ],
    importpath = "github.com/cubbit/cubbit/client/cli/utils",
    visibility = ["//visibility:public"],
)
