name: Generic ci - noop
on:
  pull_request:
    paths-ignore:
      - "main.go"
      - "src/**"
      - "constants/**"
      - "utils/**"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: 'echo "No build required"'
