name: Push version

on:
  pull_request:
    types:
      - closed

jobs:
  push-version:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      
    if: github.event.pull_request.head.ref == 'feat/bump-version-action' && github.event.pull_request.merged == true

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get latest tag from .cz.yaml
        id: latest_tag
        run: |
          latest_tag=$(grep 'version:' .cz.yaml | cut -d ':' -f 2)
          echo "tag=$latest_tag" >> $GITHUB_OUTPUT

      - name: Show latest tag
        run: echo "Latest tag is ${{ steps.latest_tag.outputs.tag }}"

      - name: Push Tag
        run: |
          git tag ${{ steps.latest_tag.outputs.tag }}
          git push origin ${{ steps.latest_tag.outputs.tag }}
